version: '3'
   
services:
  bot:
    build: .
    ports:
      - '9292:9292'
    volumes:
      - '.:/usr/src/app'
    environment:
      - LANG=C.UTF-8
    env_file:
      - .env
    stdin_open: true
    tty: true

volumes:
  db_data:
